name: Docker Prod

on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Create env file
        run: |
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo TOKEN=${{ secrets.TOKEN }} >> .env
          echo ADMIN_ROLE=${{ secrets.ADMIN_ROLE }} >> .env
          echo TOURNAMENT_JOIN_LEAVE_CHANNEL_ID=${{ secrets.TOURNAMENT_JOIN_LEAVE_CHANNEL }} >> .env
          echo TOURNAMENT_INFO_CHANNEL_ID=${{ secrets.TOURNAMENT_INFO_CHANNEL_ID }} >> .env
          cat .env

      - name: Docker run
        run: docker compose up -d --force-recreate --build
